name: GitHub Security Report Action
description: Generates security reports for a GitHub repository
author: Peter Murray

inputs:
  token:
    description: GitHub Access Token with permissions for securoty events access on the repository.
    default: ${{ github.token }}

  outputDir:
    description: The output directory for the generated report(s).
    required: true
    default: ${{ github.workspace }}

  repository:
    description: Repository name with owner. For example, peter-murray/github-security-report
    required: true
    default: ${{ github.repository }}

  sarif_report_id:
    description: The latest SARIF report id to use for the analysis of the code scanning results, if not specified the latest report will be used for the target ref.
    required: false

  ref:
    description: The ref for the target to get the code scanning findings for
    required: true
    default: ${{ github.ref }}

  sha:
    description: The SHA of the HEAD of the ref for the scanning results
    required: true
    default: ${{ github.sha }}

  https_proxy:
    description: An optional explicit proxy to use for accessing the GitHub API. Will fall back to environment variables for the proxy if this is not set and one of HTTPS_PROXY, HTTP_PROXY or lower case equivalents are present.
    required: false

runs:
  using: node20
  main: dist/index.js

branding:
  icon: shield
  color: green