name: Build and Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        env:
          GH_TOKEN: ${{ secrets.SECURITY_TOKEN }}
        run: npm test
