name: Manual Test Repository

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Invoke Action
        uses: ./
        with:
          token: ${{ secrets.SECURITY_TOKEN }}
          outputDir: .
          repository: octodemo/ghas-reporting

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: ./*.pdf
